// Market data with 5 categories and 30+ Delhi marketplaces

export const MARKET_CATEGORIES = [
  {
    id: 'malls',
    name: 'Modern Malls',
    icon: '🏬',
    color: '#FF8C00'
  },
  {
    id: 'traditional',
    name: 'Traditional Bazaars',
    icon: '🏪',
    color: '#e74c3c'
  },
  {
    id: 'street-market',
    name: 'Street Markets',
    icon: '🛍️',
    color: '#2ecc71'
  },
  {
    id: 'jewellery',
    name: 'Jewellery Markets',
    icon: '💎',
    color: '#f39c12'
  },
  {
    id: 'wholesale',
    name: 'Wholesale Markets',
    icon: '📦',
    color: '#9b59b6'
  }
];

export const MARKET_ITEMS = [
  // Modern Malls (7 items)
  {
    id: 'market-1',
    name: 'DLF Mall of India',
    category: 'malls',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7ea0bb63?w=400',
    description: 'India\'s largest shopping mall with 350+ brands',
    location: 'Sector 18, Noida',
    nearestMetro: 'Noida City Centre (Blue Line)',
    metroDistance: '10 minutes drive',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹100-150\nBus: 319, 341, 348',
    marketInfo: 'Spread over 2 million sq ft\nInternational and Indian brands\nFood court and restaurants',
    highlights: ['Shopping', 'Movies', 'Dining', 'Entertainment'],
    navigateCoordinates: '28.5921, 77.3534',
    bestTime: '11:00 AM - 10:00 PM',
    priceRange: 'Budget to Premium',
    ratings: 4.6
  },
  {
    id: 'market-2',
    name: 'Select CITYWALK',
    category: 'malls',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7ea0bb63?w=400',
    description: 'Premium shopping complex in New Delhi',
    location: 'Saket, New Delhi',
    nearestMetro: 'Saket (Blue Line)',
    metroDistance: '5 minutes walk',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹50-80\nBus: 405, 410',
    marketInfo: 'Premium international brands\nGourmet food options\nLuxury shopping destination',
    highlights: ['Designer Brands', 'High-end Dining', 'Entertainment'],
    navigateCoordinates: '28.5244, 77.1963',
    bestTime: '10:00 AM - 10:00 PM',
    priceRange: 'Premium',
    ratings: 4.7
  },
  {
    id: 'market-3',
    name: 'Ambience Mall',
    category: 'malls',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7ea0bb63?w=400',
    description: 'Luxury mall in Vasant Kunj',
    location: 'Vasant Kunj, New Delhi',
    nearestMetro: 'Malviya Nagar (Blue Line)',
    metroDistance: '15 minutes drive',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹80-120\nBus: 401, 402',
    marketInfo: '250+ international brands\nPremium dining experience\nMultiplex cinema',
    highlights: ['Shopping', 'Cinema', 'Dining', 'Luxury Brands'],
    navigateCoordinates: '28.5213, 77.1887',
    bestTime: '10:00 AM - 10:00 PM',
    priceRange: 'Premium',
    ratings: 4.5
  },
  {
    id: 'market-4',
    name: 'Pacific Mall',
    category: 'malls',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7ea0bb63?w=400',
    description: 'Fashion and lifestyle mall in Dwarka',
    location: 'Dwarka, New Delhi',
    nearestMetro: 'Dwarka Sector 8 (Blue Line)',
    metroDistance: '8 minutes walk',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹60-100\nBus: 422, 501',
    marketInfo: 'Fashion brands and lifestyle stores\nFood court with diverse cuisines\nFamily entertainment zone',
    highlights: ['Fashion', 'Electronics', 'Food', 'Entertainment'],
    navigateCoordinates: '28.5922, 77.0444',
    bestTime: '11:00 AM - 10:00 PM',
    priceRange: 'Mid-range to Premium',
    ratings: 4.4
  },
  {
    id: 'market-5',
    name: 'Krishnaa Mall',
    category: 'malls',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7ea0bb63?w=400',
    description: 'Entertainment and shopping mall',
    location: 'Pitampura, Delhi',
    nearestMetro: 'Pitampura (Blue Line)',
    metroDistance: '5 minutes walk',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹40-60\nBus: 311, 316',
    marketInfo: 'Multi-level shopping complex\nGames and entertainment\nFood and beverage outlets',
    highlights: ['Shopping', 'Gaming', 'Entertainment', 'Food Court'],
    navigateCoordinates: '28.7495, 77.1196',
    bestTime: '10:00 AM - 9:30 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.3
  },
  {
    id: 'market-6',
    name: 'Nexus Mall Pearls',
    category: 'malls',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7ea0bb63?w=400',
    description: 'Premier shopping destination in Sector 62',
    location: 'Noida Expressway, Noida',
    nearestMetro: 'Noida City Centre (Blue Line)',
    metroDistance: '20 minutes drive',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹120-150\nBus: 319, 348',
    marketInfo: '200+ national and international brands\nHigh-end restaurants\nLuxury jewelry section',
    highlights: ['Shopping', 'Dining', 'Jewelry', 'Entertainment'],
    navigateCoordinates: '28.5879, 77.3708',
    bestTime: '11:00 AM - 10:00 PM',
    priceRange: 'Premium',
    ratings: 4.6
  },
  {
    id: 'market-7',
    name: 'Inorbit Mall',
    category: 'malls',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7ea0bb63?w=400',
    description: 'Family-friendly shopping and entertainment',
    location: 'New Delhi',
    nearestMetro: 'Rajiv Chowk (Blue/Yellow Line)',
    metroDistance: '10 minutes drive',
    transportConnectivity: 'Metro: Blue/Yellow Line\nAuto: ₹70-100\nBus: 403, 420',
    marketInfo: '150+ retail brands\nMultiple dining options\nKids play area',
    highlights: ['Shopping', 'Entertainment', 'Family Activities', 'Dining'],
    navigateCoordinates: '28.6293, 77.2045',
    bestTime: '10:00 AM - 9:30 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.3
  },

  // Traditional Bazaars (8 items)
  {
    id: 'market-8',
    name: 'Chandni Chowk Market',
    category: 'traditional',
    image: 'https://images.unsplash.com/photo-1610760139106-36d6fd0a1998?w=400',
    description: 'Historic market with 400 years of heritage',
    location: 'Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '2 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹20-40\nBus: 52, 231, 232',
    marketInfo: 'Famous for textiles, electronics, jewelry\nWeb of narrow lanes\nTraditional spices and sweet shops',
    highlights: ['Textiles', 'Jewelry', 'Electronics', 'Spices', 'Sweets'],
    navigateCoordinates: '28.6502, 77.2315',
    bestTime: '9:00 AM - 8:00 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.5
  },
  {
    id: 'market-9',
    name: 'Sadar Bazaar',
    category: 'traditional',
    image: 'https://images.unsplash.com/photo-1610760139106-36d6fd0a1998?w=400',
    description: 'Wholesale and retail market complex',
    location: 'Chandni Chowk, Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '8 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹40-60\nBus: 231, 232',
    marketInfo: 'Largest wholesale market\nElectronics and utensils\nClothing and fabrics',
    highlights: ['Wholesale Items', 'Electronics', 'Kitchen Utensils', 'Fabrics'],
    navigateCoordinates: '28.6478, 77.2281',
    bestTime: '8:00 AM - 8:00 PM',
    priceRange: 'Budget',
    ratings: 4.3
  },
  {
    id: 'market-10',
    name: 'Jama Masjid Market',
    category: 'traditional',
    image: 'https://images.unsplash.com/photo-1610760139106-36d6fd0a1998?w=400',
    description: 'Bustling market around historic Jama Masjid',
    location: 'Jama Masjid, Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '5 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹30-50\nBus: 52, 231',
    marketInfo: 'Traditional clothing and accessories\nSpice market\nCurry shops and sweet vendors',
    highlights: ['Clothing', 'Accessories', 'Spices', 'Food Items'],
    navigateCoordinates: '28.6505, 77.2302',
    bestTime: '8:00 AM - 9:00 PM',
    priceRange: 'Budget',
    ratings: 4.4
  },
  {
    id: 'market-11',
    name: 'Lajpat Nagar Market',
    category: 'traditional',
    image: 'https://images.unsplash.com/photo-1610760139106-36d6fd0a1998?w=400',
    description: 'Charming market with heritage charm',
    location: 'Lajpat Nagar, New Delhi',
    nearestMetro: 'Lajpat Nagar (Pink Line)',
    metroDistance: '5 minutes walk',
    transportConnectivity: 'Metro: Pink Line\nAuto: ₹50-70\nBus: 401, 402',
    marketInfo: 'Boutiques and traditional shops\nClothing and jewelry\nCafes and restaurants',
    highlights: ['Fashion', 'Jewelry', 'Boutiques', 'Cafes'],
    navigateCoordinates: '28.5679, 77.2422',
    bestTime: '10:00 AM - 8:00 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.5
  },
  {
    id: 'market-12',
    name: 'Karol Bagh Market',
    category: 'traditional',
    image: 'https://images.unsplash.com/photo-1610760139106-36d6fd0a1998?w=400',
    description: 'Busy commercial center with diverse products',
    location: 'Karol Bagh, Delhi',
    nearestMetro: 'Karol Bagh (Blue Line)',
    metroDistance: '3 minutes walk',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹30-50\nBus: 302, 316',
    marketInfo: 'Clothing, footwear, and accessories\nElectronics and gadgets\nFootwear specialty',
    highlights: ['Footwear', 'Clothing', 'Electronics', 'Accessories'],
    navigateCoordinates: '28.6461, 77.1874',
    bestTime: '10:00 AM - 8:30 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.4
  },
  {
    id: 'market-13',
    name: 'Dariba Kalan',
    category: 'traditional',
    image: 'https://images.unsplash.com/photo-1610760139106-36d6fd0a1998?w=400',
    description: 'Historic jewelry market of Delhi',
    location: 'Chandni Chowk, Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '10 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹50-70\nBus: 231, 232',
    marketInfo: '300+ year old jewel market\nSilver and gold jewelry\nAuthentic craftsmanship',
    highlights: ['Gold Jewelry', 'Silver Items', 'Precious Stones', 'Gems'],
    navigateCoordinates: '28.6488, 77.2297',
    bestTime: '10:00 AM - 7:00 PM',
    priceRange: 'Mid-range to Premium',
    ratings: 4.6
  },
  {
    id: 'market-14',
    name: 'Nai Sarak',
    category: 'traditional',
    image: 'https://images.unsplash.com/photo-1610760139106-36d6fd0a1998?w=400',
    description: 'Famous book and stationery market',
    location: 'Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '12 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹50-70\nBus: 201, 231',
    marketInfo: 'Largest book market in Asia\nStationery and office supplies\nEducational materials',
    highlights: ['Books', 'Stationery', 'Magazines', 'Educational Materials'],
    navigateCoordinates: '28.6516, 77.2265',
    bestTime: '10:00 AM - 7:00 PM',
    priceRange: 'Budget',
    ratings: 4.5
  },

  // Street Markets (7 items)
  {
    id: 'market-15',
    name: 'Rajouri Garden Market',
    category: 'street-market',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Vibrant street market with local flavors',
    location: 'Rajouri Garden, West Delhi',
    nearestMetro: 'Rajouri Garden (Blue Line)',
    metroDistance: '3 minutes walk',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹40-60\nBus: 301, 317',
    marketInfo: 'Clothing, shoes, and accessories\nFood and beverages\nLocal lifestyle products',
    highlights: ['Fashion', 'Food', 'Accessories', 'Local Products'],
    navigateCoordinates: '28.6717, 77.0842',
    bestTime: '10:00 AM - 8:00 PM',
    priceRange: 'Budget',
    ratings: 4.3
  },
  {
    id: 'market-16',
    name: 'South Extension',
    category: 'street-market',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Upscale shopping and dining destination',
    location: 'South Delhi',
    nearestMetro: 'South Extension (Violet Line)',
    metroDistance: '5 minutes walk',
    transportConnectivity: 'Metro: Violet Line\nAuto: ₹60-80\nBus: 401, 402',
    marketInfo: 'Premium boutiques and designer stores\nMultiple dining options\nLuxury brands',
    highlights: ['Designer Brands', 'Fashion', 'Dining', 'Lifestyle'],
    navigateCoordinates: '28.5560, 77.2101',
    bestTime: '10:00 AM - 8:00 PM',
    priceRange: 'Mid-range to Premium',
    ratings: 4.6
  },
  {
    id: 'market-17',
    name: 'Hauz Khas Village Market',
    category: 'street-market',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Historic village market with trendy vibe',
    location: 'Hauz Khas, New Delhi',
    nearestMetro: 'Green Park (Green Line)',
    metroDistance: '10 minutes drive',
    transportConnectivity: 'Auto: ₹80-100\nBus: 406, 414',
    marketInfo: 'Art galleries and studios\nTrendy boutiques\nRooftop restaurants and cafes',
    highlights: ['Art & Crafts', 'Fashion', 'Dining', 'Entertainment'],
    navigateCoordinates: '28.5244, 77.1963',
    bestTime: '2:00 PM - 11:00 PM',
    priceRange: 'Mid-range to Premium',
    ratings: 4.7
  },
  {
    id: 'market-18',
    name: 'Nehrů Place Market',
    category: 'street-market',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Central Delhi shopping and entertainment',
    location: 'New Delhi',
    nearestMetro: 'Rajiv Chowk (Blue/Yellow Line)',
    metroDistance: '5 minutes walk',
    transportConnectivity: 'Metro: Blue/Yellow Line\nAuto: ₹40-60\nBus: 403, 420',
    marketInfo: 'Shopping complex with brands\nFood court\nEntertainment options',
    highlights: ['Shopping', 'Food', 'Entertainment', 'Brands'],
    navigateCoordinates: '28.6318, 77.2197',
    bestTime: '10:00 AM - 8:00 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.4
  },
  {
    id: 'market-19',
    name: 'Defence Colony Market',
    category: 'street-market',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Upscale neighborhood market',
    location: 'Defence Colony, South Delhi',
    nearestMetro: 'Kalkaji Mandir (Blue Line)',
    metroDistance: '10 minutes drive',
    transportConnectivity: 'Auto: ₹70-100\nBus: 401, 405',
    marketInfo: 'Specialty stores and boutiques\nRestaurants and cafes\nBookstores',
    highlights: ['Fashion', 'Books', 'Dining', 'Specialty Items'],
    navigateCoordinates: '28.5627, 77.2445',
    bestTime: '10:00 AM - 8:00 PM',
    priceRange: 'Mid-range',
    ratings: 4.5
  },
  {
    id: 'market-20',
    name: 'Saket District Center',
    category: 'street-market',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Modern shopping and dining complex',
    location: 'Saket, New Delhi',
    nearestMetro: 'Saket (Blue Line)',
    metroDistance: '2 minutes walk',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹50-70\nBus: 405, 410',
    marketInfo: 'Shopping and entertainment\nMultiple restaurants\nCinema and gaming',
    highlights: ['Shopping', 'Dining', 'Entertainment', 'Cinema'],
    navigateCoordinates: '28.5244, 77.1963',
    bestTime: '11:00 AM - 10:00 PM',
    priceRange: 'Mid-range to Premium',
    ratings: 4.6
  },
  {
    id: 'market-21',
    name: 'Pacific Chowk',
    category: 'street-market',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Street market with street food',
    location: 'Dwarka, New Delhi',
    nearestMetro: 'Dwarka Sector 8 (Blue Line)',
    metroDistance: '8 minutes walk',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹50-80\nBus: 422, 501',
    marketInfo: 'Street food stalls\nClothing and accessories\nLocal brands',
    highlights: ['Street Food', 'Fashion', 'Accessories', 'Entertainment'],
    navigateCoordinates: '28.5922, 77.0444',
    bestTime: '11:00 AM - 9:00 PM',
    priceRange: 'Budget',
    ratings: 4.2
  },

  // Jewellery Markets (5 items)
  {
    id: 'market-22',
    name: 'Dariba Gold Market',
    category: 'jewellery',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400',
    description: 'Premium gold and jewelry hub',
    location: 'Dariba Kalan, Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '10 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹50-70\nBus: 231, 232',
    marketInfo: 'Gold, silver, and precious stones\n300+ year heritage\nAuthentic jewelry',
    highlights: ['Gold', 'Silver', 'Diamonds', 'Precious Stones'],
    navigateCoordinates: '28.6488, 77.2297',
    bestTime: '10:00 AM - 7:00 PM',
    priceRange: 'Premium',
    ratings: 4.7
  },
  {
    id: 'market-23',
    name: 'Kasturba Nagar Jewelry Market',
    category: 'jewellery',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400',
    description: 'Traditional jewelry market',
    location: 'Kasturba Nagar, New Delhi',
    nearestMetro: 'Kasturba Nagar (Red Line)',
    metroDistance: '5 minutes walk',
    transportConnectivity: 'Metro: Red Line\nAuto: ₹40-60\nBus: 416, 418',
    marketInfo: 'Gold and diamond jewelry\nWedding collections\nCustom jewelry design',
    highlights: ['Gold Jewelry', 'Diamonds', 'Custom Designs', 'Wedding Jewelry'],
    navigateCoordinates: '28.6528, 77.2276',
    bestTime: '10:00 AM - 8:00 PM',
    priceRange: 'Premium',
    ratings: 4.6
  },
  {
    id: 'market-24',
    name: 'Subhash Nagar Jewelry Market',
    category: 'jewellery',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400',
    description: 'Budget-friendly jewelry market',
    location: 'Subhash Nagar, West Delhi',
    nearestMetro: 'Subhash Nagar (Blue Line)',
    metroDistance: '3 minutes walk',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹30-50\nBus: 303, 317',
    marketInfo: 'Affordable gold and jewelry\nTraditional designs\nModern collections',
    highlights: ['Gold', 'Silver', 'Affordable', 'Traditional Designs'],
    navigateCoordinates: '28.6619, 77.0947',
    bestTime: '10:00 AM - 8:00 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.4
  },
  {
    id: 'market-25',
    name: 'Chandni Chowk Gold Market',
    category: 'jewellery',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400',
    description: 'Famous gold trading center',
    location: 'Chandni Chowk, Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '2 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹20-40\nBus: 52, 231, 232',
    marketInfo: 'Gold and silver trading\nJewelry making shops\nAuthentic pieces',
    highlights: ['Gold Trading', 'Silver Jewelry', 'Authentic Pieces', 'Designs'],
    navigateCoordinates: '28.6502, 77.2315',
    bestTime: '9:00 AM - 7:00 PM',
    priceRange: 'Mid-range to Premium',
    ratings: 4.5
  },
  {
    id: 'market-26',
    name: 'Karol Bagh Jewelry Section',
    category: 'jewellery',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400',
    description: 'Traditional and modern jewelry',
    location: 'Karol Bagh, Delhi',
    nearestMetro: 'Karol Bagh (Blue Line)',
    metroDistance: '5 minutes walk',
    transportConnectivity: 'Metro: Blue Line\nAuto: ₹40-60\nBus: 302, 316',
    marketInfo: 'Gold, silver, and fashion jewelry\nWedding collections\nVariety of designs',
    highlights: ['Gold Jewelry', 'Silver', 'Fashion Jewelry', 'Wedding Designs'],
    navigateCoordinates: '28.6461, 77.1874',
    bestTime: '10:00 AM - 8:30 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.3
  },

  // Wholesale Markets (3 items)
  {
    id: 'market-27',
    name: 'Bhagirath Palace Market',
    category: 'wholesale',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Largest lighting and electrical goods market',
    location: 'Chandni Chowk, Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '8 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹40-60\nBus: 231, 232',
    marketInfo: 'Electrical appliances and lighting\nWholesale and retail\nLarge selection',
    highlights: ['Electronics', 'Lighting', 'Appliances', 'Electrical Goods'],
    navigateCoordinates: '28.6492, 77.2298',
    bestTime: '9:00 AM - 7:00 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.4
  },
  {
    id: 'market-28',
    name: 'Chandni Chowk Sadar Bazar Electronics',
    category: 'wholesale',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Wholesale electronics and gadgets',
    location: 'Sadar Bazar, Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '8 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹40-60\nBus: 231, 232',
    marketInfo: 'Electronics and gadgets wholesale\nMobile phones and accessories\nComputer equipment',
    highlights: ['Electronics', 'Phones', 'Gadgets', 'Accessories'],
    navigateCoordinates: '28.6478, 77.2281',
    bestTime: '9:00 AM - 7:00 PM',
    priceRange: 'Budget',
    ratings: 4.3
  },
  {
    id: 'market-29',
    name: 'Okhla Industrial Area',
    category: 'wholesale',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Large industrial and wholesale market',
    location: 'Okhla, South Delhi',
    nearestMetro: 'Okhla NSIC (Violet Line)',
    metroDistance: '10 minutes walk',
    transportConnectivity: 'Metro: Violet Line\nAuto: ₹80-120\nBus: 440, 441',
    marketInfo: 'Industrial goods and equipment\nWholesale products\nBulk purchasing',
    highlights: ['Industrial Goods', 'Wholesale Products', 'Equipment', 'Bulk Items'],
    navigateCoordinates: '28.5297, 77.2506',
    bestTime: '9:00 AM - 6:00 PM',
    priceRange: 'Budget',
    ratings: 4.2
  },
  {
    id: 'market-30',
    name: 'Chawri Bazaar Textiles',
    category: 'wholesale',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Wholesale textiles and fabrics market',
    location: 'Chawri Bazaar, Old Delhi',
    nearestMetro: 'Chandni Chowk (Yellow Line)',
    metroDistance: '12 minutes walk',
    transportConnectivity: 'Metro: Yellow Line\nAuto: ₹50-70\nBus: 201, 231',
    marketInfo: 'Fabrics and textiles wholesale\nCloth varieties\nBulk and retail',
    highlights: ['Textiles', 'Fabrics', 'Cloth', 'Wholesale'],
    navigateCoordinates: '28.6520, 77.2340',
    bestTime: '9:00 AM - 7:00 PM',
    priceRange: 'Budget',
    ratings: 4.3
  },
  {
    id: 'market-31',
    name: 'Lajpat Nagar Sadar Bazar',
    category: 'wholesale',
    image: 'https://images.unsplash.com/photo-1486572788984-e8652fad796f?w=400',
    description: 'Mixed wholesale and retail market',
    location: 'Lajpat Nagar, New Delhi',
    nearestMetro: 'Lajpat Nagar (Pink Line)',
    metroDistance: '5 minutes walk',
    transportConnectivity: 'Metro: Pink Line\nAuto: ₹50-70\nBus: 401, 402',
    marketInfo: 'Clothing and accessories wholesale\nMultiple product categories\nBulk discounts',
    highlights: ['Clothing', 'Accessories', 'Wholesale', 'Bulk Items'],
    navigateCoordinates: '28.5679, 77.2422',
    bestTime: '9:00 AM - 7:00 PM',
    priceRange: 'Budget to Mid-range',
    ratings: 4.4
  }
];

// Helper function to get market items by category
export const getMarketItemsByCategory = (categoryId) => {
  return MARKET_ITEMS.filter(item => item.category === categoryId);
};

// Helper function to get market item by id
export const getMarketItemById = (itemId) => {
  return MARKET_ITEMS.find(item => item.id === itemId);
};

// Helper function to get category details
export const getMarketCategoryDetails = (categoryId) => {
  return MARKET_CATEGORIES.find(cat => cat.id === categoryId);
};
